-- Fix newsletter database encoding issues
-- This removes the problematic base64url encoding functions and triggers

-- Drop the trigger first
DROP TRIGGER IF EXISTS newsletter_unsubscribe_token ON newsletter_subscribers;

-- Drop the trigger function
DROP FUNCTION IF EXISTS set_unsubscribe_token();

-- Drop the token generation function
DROP FUNCTION IF EXISTS generate_unsubscribe_token();

-- Drop views that depend on the unsubscribe_token column
DROP VIEW IF EXISTS active_subscribers;

-- Update existing records that might have NULL tokens
-- Generate simple random tokens for existing records without tokens
UPDATE newsletter_subscribers 
SET unsubscribe_token = encode(gen_random_bytes(32), 'hex')
WHERE unsubscribe_token IS NULL;

-- Now we can safely alter the column type
ALTER TABLE newsletter_subscribers 
ALTER COLUMN unsubscribe_token TYPE VARCHAR(128);

-- Recreate the active_subscribers view
CREATE VIEW active_subscribers AS
SELECT 
    ns.*,
    COUNT(nel.id) as total_emails_sent,
    MAX(nel.sent_at) as last_email_sent
FROM newsletter_subscribers ns
LEFT JOIN newsletter_email_log nel ON ns.id = nel.subscriber_id
WHERE ns.is_active = TRUE 
    AND ns.unsubscribed_at IS NULL 
    AND ns.deleted_at IS NULL
GROUP BY ns.id
ORDER BY ns.subscribed_at DESC;

-- Add a comment explaining the change
COMMENT ON COLUMN newsletter_subscribers.unsubscribe_token IS 'Unsubscribe token generated by application (hex encoded)';
